# Copyright (C) 2021 Square, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[versions]
kotlin = "2.3.10"
okhttp = "5.3.2"
protobuf = "3.25.8"
robovm = "2.3.14"
kotlinx-serialization = "1.10.0"
autoService = "1.1.1"
incap = "1.0.0"
jackson = "2.21.0"

[libraries]
androidPlugin = "com.android.tools.build:gradle:9.0.0"
robovmPlugin = { module = "com.mobidevelop.robovm:robovm-gradle-plugin", version.ref = "robovm" }
dokkaPlugin = "org.jetbrains.dokka:dokka-gradle-plugin:2.1.0"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.36.0"
spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:8.2.1"

kotlin-stdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

errorpronePlugin = "net.ltgt.gradle:gradle-errorprone-plugin:4.4.0"
errorproneCore = { module = "com.google.errorprone:error_prone_core", version = "2.10.0" }
errorproneJavac = { module = "com.google.errorprone:javac", version = "9+181-r4173-1" }

animalSnifferPlugin = "ru.vyarus:gradle-animalsniffer-plugin:2.0.1"
animalSnifferAnnotations = { module = "org.codehaus.mojo:animal-sniffer-annotations", version = "1.26" }

protobufPlugin = "com.google.protobuf:protobuf-gradle-plugin:0.9.6"
protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-proto = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
okhttp-client = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
junit = { module = "junit:junit", version = "4.13.2" }
truth = "com.google.truth:truth:1.4.5"
guava = { module = "com.google.guava:guava", version = "33.5.0-jre" }
android = { module = "com.google.android:android", version = "4.1.1.4" }
findBugsAnnotations = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
androidxTestRunner = { module = "androidx.test:runner", version = "1.4.0" }
rxjava = { module = "io.reactivex:rxjava", version = "1.3.8" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.21" }
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version = "3.1.12" }
reactiveStreams = { module = "org.reactivestreams:reactive-streams", version = "1.0.4" }
scalaLibrary = { module = "org.scala-lang:scala-library", version = "2.13.18" }
gson = { module = "com.google.code.gson:gson", version = "2.13.2" }
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jacksonDataformatCbor = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor", version.ref = "jackson" }
jaxbApi = { module = "javax.xml.bind:jaxb-api", version = "2.3.1" }
jaxbImpl = { module = "org.glassfish.jaxb:jaxb-runtime", version = "4.0.6" }
jaxb3Api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version = "3.0.1" }
jaxb3Impl = { module = "com.sun.xml.bind:jaxb-impl", version = "3.0.2" }
moshi = { module = "com.squareup.moshi:moshi", version = "1.15.2" }
simpleXml = { module = "org.simpleframework:simple-xml", version = "2.7.1" }
wireRuntime = { module = "com.squareup.wire:wire-runtime", version = "5.5.0" }
jsoup = { module = "org.jsoup:jsoup", version = "1.22.1" }
robovm = { module = "com.mobidevelop.robovm:robovm-rt", version.ref = "robovm" }
googleJavaFormat = "com.google.googlejavaformat:google-java-format:1.33.0"
ktfmt = "com.facebook:ktfmt:0.61"
compileTesting = "com.google.testing.compile:compile-testing:0.23.0"
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector:1.21"
